### ISSUE TITLE
Thanks for the open source, but I'm having some problems running it

### ISSUE THREAD

**Issue by Yaochangyu00** [GuanSuns/LLMs-World-Models-for-Planning#2]
@GuanSuns Thank you very much for your team's open source. It is very valuable for using large language models to output PDDL files.And I can’t wait to know when your team can open source the entire code, because for the currently public project part, after the operation is completed, the output is some predicate and action descriptions. If you want to integrate the two into a standard The PDDL file still needs further work, such as standardizing the syntax in the output action file and removing some unnecessary explanations, before it can finally be used in some domain-independent planners.

**Comment by GuanSuns** [comment]
Hi @Yaochangyu00 , to use addict, you need to install this third-party package: https://pypi.org/project/addict/#description.

Regarding parsing the outputs from the LLM (like separating the PDDL snippets and predicate descriptions etc), we believe relevant code is provided already (for example, the outputs for the logistics domain were parsed into the following format: https://github.com/GuanSuns/LLMs-World-Models-for-Planning/blob/main/results/logistics/model_blocksworld/gpt-4_pddl.json). Relevant util functions can be found here: https://github.com/GuanSuns/LLMs-World-Models-for-Planning/blob/main/utils/pddl_output_utils.py.

Regarding converting the parsed outputs into PDDL domain and problem files, yes, this part of code has not been included yet. We are still in the middle of cleaning and refactoring relevant code. But this may take a bit longer due to the authors' busy schedules.

**Comment by Yaochangyu00** [comment]
Thank you very much for your answer. Your work has made a novel and huge contribution to this field. I look forward to you showing the complete project process in the future. I wish you success in your studies!

**Comment by Yaochangyu00** [comment]
Hi @GuanSuns  ，may I ask how much it typically costs to run a project using GPT-4 for an entire workflow? For example, when using the Household demo. I've been using the GPT-3.5-turbo model for my projects, but I often encounter errors related to tokens and the process gets terminated halfway. So, I was wondering if you have any solutions for this issue. Thank you.

**Comment by GuanSuns** [comment]
@Yaochangyu00 It doesn't cost that much to run GPT-4 if you're only generating PDDLs (I don't remember exactly, but it should be around $10-$20 or even less).

Regarding how to make a smaller model like GPT-3.5 work, this is still an open question. As we mentioned in the paper, the output of GPT-3.5 is noisy -- sometimes it keeps giving syntactically incorrect PDDLs even when detailed feedback is given -- this explains why it often uses up the entire context window before clearing the errors.

**Comment by Yaochangyu00** [comment]
Great, thank you for your response.
